# Generated by Django 5.0.6 on 2024-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='timework',
            new_name='timeWork',
        ),
        migrations.AddField(
            model_name='positionlist',
            name='timeWorkByDay',
            field=models.IntegerField(default='8'),
        ),
    ]
