# Generated by Django 5.0.6 on 2024-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_salary_positionlist_salaryoftime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
