# Generated by Django 5.0.6 on 2024-06-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildobject',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='positionlist',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
