# Generated by Django 5.0.6 on 2024-06-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_buildobject_id_alter_positionlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildobject',
            name='allowance',
            field=models.FloatField(default=1, max_length=50),
        ),
    ]
