# Generated by Django 5.0.6 on 2024-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_buildobject_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('objectsData', models.JSONField()),
            ],
        ),
    ]
