# Generated by Django 5.0.6 on 2024-06-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
