# Generated by Django 5.0.6 on 2024-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='login',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
